language : node_js

node_js:
  - 10.15.3 

branches:
  only:
  - master

install:
- yarn

script:
- yarn build

deploy:
  provider: npm
  email: javpeiwen2010@gmail.com
  api_key: "$npm_token"
  skip_cleanup: true